#!/bin/sh

uci -q delete ucitrack.@clashwrt[-1]
uci -q add ucitrack clashwrt
uci -q set ucitrack.@clashwrt[-1].init=clashwrt
uci -q commit ucitrack
uci -q delete firewall.clashwrt
uci -q set firewall.clashwrt=include
uci -q set firewall.clashwrt.type=script
uci -q set firewall.clashwrt.path=/var/etc/clashwrt.include
uci -q set firewall.clashwrt.reload=1
uci -q commit firewall

mkdir -p /etc/clashwrt/config
mkdir -p /etc/clashwrt/proxy_provider
mkdir -p /etc/clashwrt/backup
mkdir -p /etc/clashwrt/core
mkdir -p /etc/clashwrt/history
mkdir -p /usr/share/clashwrt/backup

cp -f "/etc/config/clashwrt" "/usr/share/clashwrt/backup/clashwrt" >/dev/null 2>&1
# cp -f "/etc/clashwrt/custom/clashwrt_custom_rules.list" "/usr/share/clashwrt/backup/clashwrt_custom_rules.list" >/dev/null 2>&1
# cp -f "/etc/clashwrt/custom/clashwrt_custom_rules_2.list" "/usr/share/clashwrt/backup/clashwrt_custom_rules_2.list" >/dev/null 2>&1
# cp -f "/etc/clashwrt/custom/clashwrt_custom_hosts.list" "/usr/share/clashwrt/backup/clashwrt_custom_hosts.list" >/dev/null 2>&1
# cp -f "/etc/clashwrt/custom/clashwrt_custom_fake_filter.list" "/usr/share/clashwrt/backup/clashwrt_custom_fake_filter.list" >/dev/null 2>&1
# cp -f "/etc/clashwrt/custom/clashwrt_custom_domain_dns.list" "/usr/share/clashwrt/backup/clashwrt_custom_domain_dns.list" >/dev/null 2>&1
# cp -f "/etc/clashwrt/custom/clashwrt_custom_domain_dns_policy.list" "/usr/share/clashwrt/backup/clashwrt_custom_domain_dns_policy.list" >/dev/null 2>&1
# cp -f "/etc/clashwrt/custom/clashwrt_custom_fallback_filter.yaml" "/usr/share/clashwrt/backup/clashwrt_custom_fallback_filter.yaml" >/dev/null 2>&1
# cp -f "/etc/clashwrt/custom/clashwrt_custom_netflix_domains.list" "/usr/share/clashwrt/backup/clashwrt_custom_netflix_domains.list" >/dev/null 2>&1

mkdir -p /lib/upgrade/keep.d
cat > "/lib/upgrade/keep.d/luci-app-clashwrt" <<-EOF
/etc/clashwrt/
EOF

if [ -f "/tmp/clashwrt.bak" ]; then
	mv -f "/tmp/clashwrt.bak" "/etc/config/clashwrt" >/dev/null 2>&1
	cp -rf "/tmp/clashwrt/." "/etc/clashwrt/" >/dev/null 2>&1
	cp -rf "/tmp/clashwrt_config/." "/etc/clashwrt/config/" >/dev/null 2>&1
	cp -rf "/tmp/clashwrt_core/." "/etc/clashwrt/core/" >/dev/null 2>&1
	cp -rf "/tmp/clashwrt_history/." "/etc/clashwrt/history/" >/dev/null 2>&1
	cp -rf "/tmp/clashwrt_proxy_provider/." "/etc/clashwrt/proxy_provider/" >/dev/null 2>&1
	cp -rf "/tmp/clashwrt_rule_provider/." "/etc/clashwrt/rule_provider/" >/dev/null 2>&1
	cp -rf "/tmp/clashwrt_game_rules/." "/etc/clashwrt/game_rules/" >/dev/null 2>&1
	mv -f "/tmp/clashwrt_custom_rules.list.bak" "/etc/clashwrt/custom/clashwrt_custom_rules.list" >/dev/null 2>&1
	mv -f "/tmp/clashwrt_custom_rules_2.list.bak" "/etc/clashwrt/custom/clashwrt_custom_rules_2.list" >/dev/null 2>&1
	mv -f "/tmp/clashwrt_custom_hosts.list.bak" "/etc/clashwrt/custom/clashwrt_custom_hosts.list" >/dev/null 2>&1
	mv -f "/tmp/clashwrt_custom_fake_filter.list.bak" "/etc/clashwrt/custom/clashwrt_custom_fake_filter.list" >/dev/null 2>&1
	mv -f "/tmp/clashwrt_custom_domain_dns.list.bak" "/etc/clashwrt/custom/clashwrt_custom_domain_dns.list" >/dev/null 2>&1
	rm -rf "/etc/clashwrt/clashwrt"
	rm -rf "/etc/clashwrt/fake_filter.list"
	rm -rf "/etc/clashwrt/clashwrt_servers_fake_filter.conf"
	rm -rf /tmp/clashwrt*
fi

source "/etc/openwrt_release"
case "${DISTRIB_ARCH}" in
	aarch64_*)
		CORE_ARCH="linux-armv8"
		;;
	arm_*_neon-vfp*)
		CORE_ARCH="linux-armv7"
		;;
	arm_*_neon|arm_*_vfp*)
		CORE_ARCH="linux-armv6"
		;;
	arm*)
		CORE_ARCH="linux-armv5"
		;;
	i386_*)
		CORE_ARCH="linux-386"
		;;
	mips64_*)
		CORE_ARCH="linux-mips64"
		;;
	mips_*)
		CORE_ARCH="linux-mips-softfloat"
		;;
	mipsel_*)
		CORE_ARCH="linux-mipsle-softfloat"
		;;
	x86_64)
		CORE_ARCH="linux-amd64"
		;;
	*)
		CORE_ARCH="0"
		;;
esac
uci -q set clashwrt.config.core_version="${CORE_ARCH}"

if [ -n "$(uci -q get dhcp.@dnsmasq[0].resolvfile)" ]; then
   uci -q set clashwrt.config.default_resolvfile=$(uci -q get dhcp.@dnsmasq[0].resolvfile)
fi

uci -q set clashwrt.config.enable=0
uci -q commit clashwrt

rm -f /tmp/luci-indexcache
exit 0
